# Generated by Django 5.2.8 on 2025-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_m_s_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
